### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mfocchi** [ERF2024/dog_challenge#1]
SOFTWARE:
- [x] (Andrea Pupa) change infographics and map to have 25cm width C obstacle
- [x] Q/A (14/02, at 10) ask teams: 1) type of challenge 2) ROS1 / ROS2
- [x] (Michele) add eagleproject as contributors to this organization
- [x] (Michele) Provide info on the objects to be detected
- [x] check Realsense pointcloud topic rate with wi-fi (15fps)
- [x] (Gennaro Raiola) remap topics in WOLF simulation to match real robot ones
- [x] (Eagleprojects) test if LIDAR is ok with 1 m high walls
- [x] (Eagleprojects) integrate frontal realsense and provide ros node to read topic 
- [x] (Eagleprojects) provide the topics from the real robot interface: lowcmd imu, jointstate, odom, tf, tf_static, laser and provide their average frequency of publication 
- [x] (Eagleproject) provide documentation for low level control (topics)
- [x] (Eagleprojects) provide ros bridge for teams that use ROS2 Humble (for POLITO)
- [ ] (Eagleprojects) check if Jetson Nano 9x10x3.5 m  can fit on the robot (USB connection + power supply)
- [x] (Eagleproject) CUDA version? interface with docker? (for POLITO)
- [x] (Eagleproject) provide time logger class to check the final score 
- [ ] (Eagleproject) test the possibility to add an external Nvidia Jetson Nano board

HARDWARE:
- [x] (Eagleproject) print 3D support for Realsense front, 
- [x] (Eagleproject) provide information on the onboard hardware to be used (jetson, resolution of the realsense etc.)

**Comment by mfocchi** [comment]
- [ ] Buy material for the challenge
- [ ] rent truck to move the material to palacongressi
- [ ] evaluate overall power consumption and ask Palacongressi enough plugs for the challenge

**Comment by marco-ambrogi** [comment]
We tested the LIDAR on the real robot with 1 m high walls and it is OK, there are no problems. The vertical FOV is 30°. 
For any doubts relating to the technical specifications of the lidar you can refer to the pdf document located in the "docs" folder.

**Comment by giuseppecialdella** [comment]
We added the urdf equipped with Lidar and frontal Realsense camera, in addition to the already integrated cameras. 
The packages, with instructions on how to install realsense plugin, are available under the folder "simulation_tools".

**Comment by Pelliz1997** [comment]
We added the ROS topics documentation from the real robot interface, this is available in the "docs" folder.
We also added in the same folder a screenshot with info regarding Jetpack and CUDA version as requested by POLITO.

**Comment by giuseppecialdella** [comment]
We managed to implement the **ros bridge** for teams that use ROS2 Humble and we successfully verified the communication with the robot Go1. 
Please follow the guide at "https://nvidia-isaac-ros.github.io/concepts/nitros_bridge/ros1_bridge_setup.html" to build up the bridge. Once built, you can launch your ROS2 scripts.
